config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  root to: "high_voltage/pages#show", id: "root"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order(id: :desc) }

  belongs_to :user

  enum state: [:draft, :published]
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]

  def d_name
    name || email.split('@').first
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def subdomain
    request.subdomains.first
  end
  helper_method :subdomain
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def letsencrypt
    render text: "uNBIsvFHGW7lkSDMOPVrW42d2-sZ9YP4qBOHpAoGC50.gbqC8iO1DUvGv46JtsdhtnocFtc08pkZvGFXsXRobl4"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = PostPolicy::Scope.new(current_user, Post).resolve
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    authorize :post
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      authorize @post
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def navbar_link_to(name=nil, options=nil, html_options={}, &block)
    if html_options[:class].blank?
      html_options[:class] = "nav-link"
    else
      html_options[:class] += " nav-link"
    end

    content_tag(:li, class: (current_page?(options) ? 'nav-item active' : 'nav-item')) do
      link_to(name, options, html_options, &block)
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90768483-1', 'auto');
  ga('send', 'pageview');

app/views/application/_flash.html.slim
- if flash.any?
  #flash.container
    - flash.each do |k,v|
      .flash class="flash-#{k} alert #{bootstrap_class_for(k)} alert-dismissable fade show" role="alert"
        button type="button" class="close" data-dismiss="alert" aria-label="Close"
          span aria-hidden="true" &times;
        = v

app/views/application/_footer.html.slim
| &copy;2017 
= link_to("Chad Ingram", "https://github.com/matrix9180")

app/views/application/_header.html.slim
nav.navbar.navbar-toggleable.navbar-dark.bg-faded
    button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    =link_to(t(:brand), root_url, class: 'navbar-brand')
    #navbarSupportedContent.collapse.navbar-collapse
      //ul.navbar-nav.mr-auto
      //  = navbar_link_to('Home', root_url)
      - if subdomain=='admin'
        ul.navbar-nav.ml-auto
          = render 'user_nav'

app/views/application/_main.html.slim
div class="#{controller.controller_name} #{controller.action_name}" id="#{[controller.controller_name, controller.action_name, params[:id]].compact.join('-')}"
  = yield

app/views/application/_user_nav.html.slim
li#userNav.nav-item.dropdown
  = link_to('Account', nil, class: 'nav-link dropdown-toggle', id: 'myAccountDropdownMenuLink', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} )
  .dropdown-menu.dropdown-menu-right aria-labelledby="myAccountDropdownMenuLink"
    - unless signed_in?
      = link_to('Log In', new_user_session_url, class: 'dropdown-item')
      = link_to('Sign Up', new_user_registration_url, class: 'dropdown-item')
    - else
      .dropdown-header
        | Signed in as
        br
        strong
          = current_user.d_name
      .dropdown-divider
      //= link_to('Your Profile', user_url(current_user), class: 'dropdown-item')
      .dropdown-divider
      //= link_to('Edit Profile', edit_me_url, class: 'dropdown-item')
      = link_to('Log Out', destroy_user_session_url, method: :delete, class: 'dropdown-item')

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t(:brand)
    = csrf_meta_tags
    meta name="repo-url" content="https://github.com/matrix9180/io/tree/#{ENV.fetch("HEROKU_SLUG_COMMIT") { "master" } }"
    = favicon_link_tag('favicon-32.png')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header#header
      = render 'header'
    = render 'flash'
    main#main
      = render 'main'
    footer#footer
      = render 'footer'
    = render 'analytics'

app/views/pages/letsencrypt.html.slim
h1 Pages#letsencrypt
p Find me in app/views/pages/letsencrypt.html.slim

app/views/pages/root.html.slim
h1 Coming Soon.

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.input :title
  = f.input :body
  = f.input :state, collection: [:draft, :published], as: :select
  = f.button :submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Title
      th User
      th Body
      th State
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.user
        td = post.body
        td = post.state
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong User:
  = @post.user
p
  strong Body:
  == Kramdown::Document.new(@post.body).to_html
p
  strong State:
  = @post.state

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path